/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUIVIEW;

import BLL.Consumator;
import DAL.ConsumatorRepository;
import DAL.CrudFormException;
import GUIMODEL.ConsumatorTableModel;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author CyberTech
 */
public class AdminDashboardConsumator extends javax.swing.JInternalFrame {

    /**
     * Creates new form DashboardLibrarian
     */
    private ConsumatorRepository cr = new ConsumatorRepository();
    private ConsumatorTableModel ctm = new ConsumatorTableModel();
    
    
    public AdminDashboardConsumator() throws CrudFormException {
        initComponents();
        loadTable();
    }
    
    private void loadTable(){
        try{
        List<Consumator> lists = cr.findAll();
        ctm.addListConsumator(lists);
        jTableConsumator.setModel(ctm);
        ctm.fireTableDataChanged();
        }catch(CrudFormException e){
            e.getMessage();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtnCreateConsumator = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsumator = new javax.swing.JTable();
        jbtnDelete = new javax.swing.JButton();
        jbtnEdit = new javax.swing.JButton();

        setBorder(null);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(642, 505));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("CONSUMATOR");

        jbtnCreateConsumator.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnCreateConsumator.setText("CREATE");
        jbtnCreateConsumator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCreateConsumatorActionPerformed(evt);
            }
        });

        jTableConsumator.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "First name", "Last name", "Adress", "City", "Tel. Number", "Birthday", "null"
            }
        ));
        jScrollPane1.setViewportView(jTableConsumator);

        jbtnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnDelete.setText("DELETE");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        jbtnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnEdit.setText("EDIT");
        jbtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnCreateConsumator, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jbtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jbtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jbtnCreateConsumator, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jbtnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jbtnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCreateConsumatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCreateConsumatorActionPerformed
        // TODO add your handling code here:
        JDesktopPane pane = getDesktopPane();
        pane.removeAll();
        AdminDashboardConsumatorCreate adcc = new AdminDashboardConsumatorCreate();
        pane.add(adcc).setVisible(true);
        
    }//GEN-LAST:event_jbtnCreateConsumatorActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            int row = jTableConsumator.getSelectedRow();
            if (row != -1) {
                Consumator c = ctm.getConsumatori(row);
                cr.delete(c);
                JOptionPane.showMessageDialog(this, "Deleted");
                loadTable();
            }
        } catch (CrudFormException e) {
            e.getMessage();
        }
        
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditActionPerformed
        // TODO add your handling code here:
            int row = jTableConsumator.getSelectedRow();
            if(row != -1){
                Consumator c = ctm.getConsumatori(row);
                JDesktopPane pane = getDesktopPane();
                pane.removeAll();
                AdminDashboardConsumatorEdit adcc = new AdminDashboardConsumatorEdit(c);
                pane.add(adcc).setVisible(true);
            }
    }//GEN-LAST:event_jbtnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsumator;
    private javax.swing.JButton jbtnCreateConsumator;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnEdit;
    // End of variables declaration//GEN-END:variables
}
