/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUIVIEW;

import BLL.Userlibrary;
import DAL.CrudFormException;
import DAL.UserlibraryRepository;
import GUIMODEL.LibrarianTableModel;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author CyberTech
 */
public class AdminDashboardLibrarian extends javax.swing.JInternalFrame {

    /**
     * Creates new form DashboardLibrarian
     */
    private UserlibraryRepository ur = new UserlibraryRepository();
    private LibrarianTableModel ltm = new LibrarianTableModel();
    
    
    public AdminDashboardLibrarian() throws CrudFormException {
        initComponents();
        loadTable();
    }
    
    private void loadTable(){
        try{
            List<Userlibrary> lists = ur.findAll();
            ltm.addListLibrarian(lists);
            jTableLibrarian.setModel(ltm);
            ltm.fireTableDataChanged();
        }catch(CrudFormException e){
            e.getMessage();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jbtnCreateLibrarian = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLibrarian = new javax.swing.JTable();
        jbtnDelete = new javax.swing.JButton();
        jbtnEdit = new javax.swing.JButton();

        setBorder(null);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(642, 505));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("LIBRARIAN");

        jbtnCreateLibrarian.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnCreateLibrarian.setText("CREATE");
        jbtnCreateLibrarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCreateLibrarianActionPerformed(evt);
            }
        });

        jTableLibrarian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "First name", "Last name", "Username", "Password", ""
            }
        ));
        jScrollPane1.setViewportView(jTableLibrarian);

        jbtnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnDelete.setText("DELETE");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        jbtnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jbtnEdit.setText("EDIT");
        jbtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnCreateLibrarian, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jbtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jbtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jbtnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jbtnCreateLibrarian, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCreateLibrarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCreateLibrarianActionPerformed
        // TODO add your handling code here:
        JDesktopPane pane = getDesktopPane();
        AdminDashboardLibrarianCreate adlc = new AdminDashboardLibrarianCreate();
        pane.removeAll();
        pane.add(adlc).setVisible(true);
    }//GEN-LAST:event_jbtnCreateLibrarianActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        // TODO add your handling code here:
        try {
            int row = jTableLibrarian.getSelectedRow();
            if (row != -1) {
                Userlibrary u = ltm.getUserlibrary(row);
                ur.delete(u);
                JOptionPane.showMessageDialog(this, "Delete");
                loadTable();
            }
        } catch (CrudFormException e) {
            e.getMessage();
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditActionPerformed
        // TODO add your handling code here:
        
            int row = jTableLibrarian.getSelectedRow();
            if (row != -1) {
                Userlibrary u = ltm.getUserlibrary(row);
                System.out.println(u);
                JDesktopPane pane = getDesktopPane();
                pane.removeAll();
                AdminDashboardLibrarianEdit adle = new AdminDashboardLibrarianEdit(u);
                pane.add(adle).setVisible(true);
                
            }
    }//GEN-LAST:event_jbtnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLibrarian;
    private javax.swing.JButton jbtnCreateLibrarian;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnEdit;
    // End of variables declaration//GEN-END:variables
}
