/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUIVIEW;

import BLL.Book;
import BLL.Borrowedbook;
import BLL.Consumator;
import DAL.BookRepository;
import DAL.BorrowedbookRepository;
import DAL.ConsumatorRepository;
import DAL.CrudFormException;
import GUIMODEL.BookComboBoxModel;
import GUIMODEL.ConsumatorComboBoxModel;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author CyberTech
 */
public class UserCreateBorrow extends javax.swing.JInternalFrame {
    
    //For books
    private BookRepository br = new BookRepository();
    private BookComboBoxModel cbmb = new BookComboBoxModel();
    
    //For Consumator
    private ConsumatorRepository cr = new ConsumatorRepository();
    private ConsumatorComboBoxModel ccbm = new ConsumatorComboBoxModel();
    
    //Borrowed Book
    private BorrowedbookRepository bbr = new BorrowedbookRepository();
    
    //Formater Date
    private SimpleDateFormat formaterDMY = new SimpleDateFormat("dd-MM-yyyy");
    
    /**
     * Creates new form UseCreateBorrow
     */
    public UserCreateBorrow() {
        initComponents();
        loadComboBoxBook();
        loadComboBoxConsumator();
        setDateForReceipt();
    }
    
    private void loadComboBoxBook(){
        try{
            List<Book> list = br.findAll();
            cbmb.addList(list);
            jcmbBook.setModel(cbmb);
            jcmbBook.repaint();
        }catch(CrudFormException e){
            e.getMessage();
        }
    }
    
    private void loadComboBoxConsumator(){
        try{
            List<Consumator> list = cr.findAll();
            ccbm.addList(list);
            jcmbConsumator.setModel(ccbm);
            jcmbConsumator.repaint();
        }catch(CrudFormException e){
            e.getMessage();
        }
    }
    
    private void setDateForReceipt(){
        jtfDateOfReceipt.setText(formaterDMY.format(new Date()));
    }
    
    private void calculateForDateReturn(){
        Calendar calendar = new GregorianCalendar();
        
        //Get days, and currentdays + days
        Integer days = Integer.valueOf(jtfDays.getText());
        calendar.add(Calendar.DAY_OF_MONTH,days);
        Date date1 = calendar.getTime();
        
        // set days of returns
        jtfDateofReturns.setText(formaterDMY.format(date1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcmbConsumator = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jtfDateOfReceipt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfDateofReturns = new javax.swing.JTextField();
        jtbnCreate = new javax.swing.JButton();
        jcmbBook = new javax.swing.JComboBox<>();
        jtfDays = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("BORROW A BOOK");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Book");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Consumator");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Date of Receipt");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Days");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Date of returns");

        jtbnCreate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtbnCreate.setText("CREATE");
        jtbnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnCreateActionPerformed(evt);
            }
        });

        jtfDays.setColumns(5);
        jtfDays.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDaysKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jtfDateOfReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcmbBook, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(232, 232, 232)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcmbConsumator, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtfDateofReturns, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jtfDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jtbnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jcmbConsumator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmbBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfDays, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfDateofReturns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfDateOfReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jtbnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnCreateActionPerformed
        // TODO add your handling code here:
        try {
            //Get value for creating a borrowed book
            Book b = (Book)cbmb.getSelectedItem();
            Consumator c = (Consumator)ccbm.getSelectedItem();
            Date dateofReceipt = formaterDMY.parse(jtfDateOfReceipt.getText());
            Date dateofReturn = formaterDMY.parse(jtfDateofReturns.getText());
            
            //Set value 
            Borrowedbook bb = new Borrowedbook();
            bb.setBookId(b);
            bb.setConsumatorId(c);
            bb.setDateOfReceipt(dateofReceipt);
            bb.setDateofReturn(dateofReturn);
            
            //Create 
            bbr.create(bb);
            JOptionPane.showMessageDialog(this, "Borrow book created");
            
            //Back to UserMainapge
            JDesktopPane pane = getDesktopPane();
            pane.removeAll();
            pane.add(new UserMainPage()).setVisible(true);
        } catch (CrudFormException ex) {
            ex.getMessage();
        } catch (ParseException ex) {
            ex.getMessage();
        }
    }//GEN-LAST:event_jtbnCreateActionPerformed

    private void jtfDaysKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDaysKeyPressed
        // TODO add your handling code here:
        //Press enter at jTextFieldDays to calcute the day return
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            calculateForDateReturn();
        }
    }//GEN-LAST:event_jtfDaysKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<Book> jcmbBook;
    private javax.swing.JComboBox<Consumator> jcmbConsumator;
    private javax.swing.JButton jtbnCreate;
    private javax.swing.JTextField jtfDateOfReceipt;
    private javax.swing.JTextField jtfDateofReturns;
    private javax.swing.JTextField jtfDays;
    // End of variables declaration//GEN-END:variables
}
