/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUIVIEW;

import BLL.Book;
import DAL.BookRepository;
import DAL.CrudFormException;
import GUIMODEL.BookTableModel;
import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author CyberTech
 */
public class UserBooks extends javax.swing.JInternalFrame {

    private BookTableModel btm = new BookTableModel();
    private BookRepository br = new BookRepository();

    /**
     * Creates new form UserBooks
     */
    public UserBooks() throws CrudFormException {
        initComponents();
        loadTable();
    }

    private void loadTable() throws CrudFormException {
        try {
            List<Book> lists = br.findAll();
            btm.addListBook(lists);
            jTableBooks.setModel(btm);
            btm.fireTableDataChanged();
        } catch (CrudFormException e) {
            e.getMessage();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtbnDeleteBook = new javax.swing.JButton();
        jbtnEditBook = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbtnCreateBook = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableBooks = new javax.swing.JTable();

        jtbnDeleteBook.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtbnDeleteBook.setText("DELETE");
        jtbnDeleteBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnDeleteBookActionPerformed(evt);
            }
        });

        jbtnEditBook.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnEditBook.setText("EDIT");
        jbtnEditBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditBookActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("             Set one");

        jbtnCreateBook.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnCreateBook.setText("CREATE");
        jbtnCreateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCreateBookActionPerformed(evt);
            }
        });

        jTableBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ISBN", "Book Name", "Genders", "Publication"
            }
        ));
        jScrollPane1.setViewportView(jTableBooks);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jtbnDeleteBook, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jbtnEditBook, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCreateBook, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 738, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtbnDeleteBook, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnEditBook, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnCreateBook, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbnDeleteBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnDeleteBookActionPerformed
        // TODO add your handling code here:
        try {
            int row = jTableBooks.getSelectedRow();
            if (row != -1) {
                Book b = btm.getBook(row);
                br.delete(b);
                JOptionPane.showMessageDialog(this, "Book deleted");
                loadTable();
            }
        } catch (CrudFormException e) {
            e.getMessage();
        }
    }//GEN-LAST:event_jtbnDeleteBookActionPerformed

    private void jbtnCreateBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCreateBookActionPerformed
        // TODO add your handling code here:
        JDesktopPane pane = getDesktopPane();
        pane.removeAll();
        UserBookCreate ubc = new UserBookCreate();
        pane.add(ubc).setVisible(true);
    }//GEN-LAST:event_jbtnCreateBookActionPerformed

    private void jbtnEditBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditBookActionPerformed
        // TODO add your handling code here:
        int row = jTableBooks.getSelectedRow();
        if (row != -1) {
            Book b = btm.getBook(row);
            UserBookEdit ube = new UserBookEdit(b);
            JDesktopPane pane = getDesktopPane();
            pane.removeAll();
            pane.add(ube).setVisible(true);
        }
    }//GEN-LAST:event_jbtnEditBookActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableBooks;
    private javax.swing.JButton jbtnCreateBook;
    private javax.swing.JButton jbtnEditBook;
    private javax.swing.JButton jtbnDeleteBook;
    // End of variables declaration//GEN-END:variables
}
