/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUIVIEW;

import DAL.CrudFormException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;

/**
 *
 * @author CyberTech
 */
public class UserMainPage extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form UserMainPage1
     */
    public UserMainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jbtnCreateBorrow = new javax.swing.JButton();
        jbtnRegisterConsumator = new javax.swing.JButton();
        jtbnSearchConsumator = new javax.swing.JButton();
        jtbnUserBorrowedbook = new javax.swing.JButton();
        jbtnBooks = new javax.swing.JButton();
        jbtnConsumator = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(820, 455));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jbtnCreateBorrow.setText("Create a borrow");
        jbtnCreateBorrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCreateBorrowActionPerformed(evt);
            }
        });

        jbtnRegisterConsumator.setText("Register Consumator");
        jbtnRegisterConsumator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegisterConsumatorActionPerformed(evt);
            }
        });

        jtbnSearchConsumator.setText("Search for Consmator");
        jtbnSearchConsumator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnSearchConsumatorActionPerformed(evt);
            }
        });

        jtbnUserBorrowedbook.setText("Book Borrowed");
        jtbnUserBorrowedbook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbnUserBorrowedbookActionPerformed(evt);
            }
        });

        jbtnBooks.setText("Books");
        jbtnBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBooksActionPerformed(evt);
            }
        });

        jbtnConsumator.setText("Consumator");
        jbtnConsumator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnConsumatorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnCreateBorrow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnRegisterConsumator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbnSearchConsumator, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnConsumator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtbnUserBorrowedbook, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCreateBorrow, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbnUserBorrowedbook, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnRegisterConsumator, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtbnSearchConsumator, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnConsumator, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnRegisterConsumatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegisterConsumatorActionPerformed
        // TODO add your handling code here:
        JDesktopPane pane = getDesktopPane();
        pane.removeAll();
        UserRegisterConsumator urc = new UserRegisterConsumator();
        pane.add(urc).setVisible(true);
    }//GEN-LAST:event_jbtnRegisterConsumatorActionPerformed

    private void jbtnBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBooksActionPerformed
        // TODO add your handling code here:
        try {
            JDesktopPane pane = getDesktopPane();
            pane.removeAll();
            UserBooks ub = new UserBooks();
             pane.add(ub).setVisible(true);
        } catch (CrudFormException e) {
           e.getMessage();
        }
    }//GEN-LAST:event_jbtnBooksActionPerformed

    private void jbtnConsumatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnConsumatorActionPerformed
        // TODO add your handling code here:
        try {
            JDesktopPane pane = getDesktopPane();
            pane.removeAll();
            UserConsumator uc = new UserConsumator();
            pane.add(uc).setVisible(true);
        } catch (CrudFormException ex) {
            ex.getMessage();
        }
        
    }//GEN-LAST:event_jbtnConsumatorActionPerformed

    private void jtbnSearchConsumatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnSearchConsumatorActionPerformed
        // TODO add your handling code here:
        try {
            JDesktopPane pane = getDesktopPane();
            pane.removeAll();
            pane.add(new UserSearchConsumator()).setVisible(true);
        } catch (CrudFormException e) {
            e.getMessage();
        }
    }//GEN-LAST:event_jtbnSearchConsumatorActionPerformed

    private void jbtnCreateBorrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCreateBorrowActionPerformed
        // TODO add your handling code here:
        JDesktopPane pane = getDesktopPane();
        pane.removeAll();
        pane.add(new UserCreateBorrow()).setVisible(true);
        
    }//GEN-LAST:event_jbtnCreateBorrowActionPerformed

    private void jtbnUserBorrowedbookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbnUserBorrowedbookActionPerformed
        // TODO add your handling code here:
        JDesktopPane pane = getDesktopPane();
        pane.removeAll();
        pane.add(new UserBorrowedbook()).setVisible(true);
    }//GEN-LAST:event_jtbnUserBorrowedbookActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtnBooks;
    private javax.swing.JButton jbtnConsumator;
    private javax.swing.JButton jbtnCreateBorrow;
    private javax.swing.JButton jbtnRegisterConsumator;
    private javax.swing.JButton jtbnSearchConsumator;
    private javax.swing.JButton jtbnUserBorrowedbook;
    // End of variables declaration//GEN-END:variables
}
